### ISSUE TITLE
use network 

### ISSUE THREAD

**Issue by SegFault42** [WerWolv/libtesla#40]
I don't know if i'm doing something wrong but i want to get my local ip address.

I init with clkrstInitialize(); the function don't return an error.

Then i try get my ip with gethostname() but when i print my ip i have 1.0.0.127

I tried in a simple homebrew and i get my local ip.

what i missed ?

**Comment by WerWolv** [comment]
You need to wrap gethostname in a  `tsl::doWithSMSession` lambda because gethostname inits and exits a service when called. This only works if SM is initialized

**Comment by HookedBehemoth** [comment]
By default libtesla closes the sm session after initializing all services.
https://github.com/switchbrew/libnx/blob/70ddae58ffae84eabefb90a1964c140d7a27145d/nx/source/runtime/resolver.c#L584
This calls nifmInitialize which requires sm.
The options you have are:
- You can call nifmInitialize in initServices and nifmExit in exitServices and it will work because of the way the service guard inside libnx works. This will keep the nifm service handle over the entire runtime.
- keep an sm open over the entire runtime of your application similar to the above option
- you do what WerWolv suggested and wrap every call to gethostname in `tsl::doWithSMSession`
